#include "dict_minimum.inc"
#include "device.inc"
#include "dict_compiler.inc"
#include "dict_interrupt.inc"
#include "words/applturnkey.S"

#include "words/udot.S"
#include "words/dot-s.S"

#include "words/dotstring.S"
#include "words/squote.S"
#include "words/show-wordlist.S"
#include "words/words.S"

#include "words/edefer.S"
#include "words/rdefer.S"
#include "words/is.S"

#include "words/d-invert.S"
#include "words/d-plus.S"
#include "words/d-minus.S"
#include "words/spirw.S"


